apiVersion: v1
kind: Namespace
metadata:
  name: web-lab














# Specifies the core Kubernetes v1 API version for core resource types
# apiVersion: v1

# Tells Kubernetes to create a Namespace object (a virtual isolated workspace)
# kind: Namespace

# Metadata section containing resource metadata for this namespace
# metadata:

# Unique name of the namespace; isolates all application resources from default namespaces
#   name: web-lab
