apiVersion: v1
kind: ConfigMap
metadata:
  name: app-2-config
  namespace: web-lab
data:
  SERVICE_NAME: "app-2"
  PORT: "8082"














# Specifies the core Kubernetes v1 API version for ConfigMap resources
# apiVersion: v1

# Tells Kubernetes what resource object to create (ConfigMap: holds non-sensitive configuration)
# kind: ConfigMap

# Metadata contains naming and namespace scope information for this ConfigMap
# metadata:

# Unique name of this ConfigMap object inside the namespace
#   name: app-2-config

# The virtual isolated namespace where this ConfigMap will reside
#   namespace: web-lab

# Data dictionary containing non-sensitive key-value environment variables
# data:

# Environment variable key defining the name of the microservice
#   SERVICE_NAME: "app-2"

# Environment variable key defining the HTTP port the Users API listens on
#   PORT: "8082"
