apiVersion: v1
kind: Secret
metadata:
  name: app-2-secret
  namespace: web-lab
stringData:
  API_KEY: "app2-secret-key-456"














# Specifies the core Kubernetes v1 API version for Secret resources
# apiVersion: v1

# Tells Kubernetes what resource object to create (Secret: holds sensitive credentials)
# kind: Secret

# Metadata contains naming and namespace scope information for this Secret
# metadata:

# Unique name of this Secret object inside the namespace
#   name: app-2-secret

# The virtual isolated namespace where this Secret will reside
#   namespace: web-lab

# Plaintext key-value pairs (Kubernetes automatically encodes them in base64 on submission)
# stringData:

# Sensitive API key secret injected into app-2 container environment
#   API_KEY: "app2-secret-key-456"
